CREATE OR REPLACE FUNCTION FUNCION_INSERTAR_BITACORA()
    RETURNS TRIGGER
    LANGUAGE plpgsql
    AS
    $$
BEGIN
INSERT INTO b_doc_ingre(USUARIO_INGRE_DOC, IP_INGRE_DOC, FECHA_INGRE_DOC, PROPIETARIO_INGRE_DOC, COD_DOC)
VALUES (NEW.USARIO_INGRE_DOC, NEW.IP_INGRE_DOC, NEW.FECHA_INGRE_DOC, NEW.PROPIETARIO_INGRE_DOC, NEW.COD_DOC);
RETURN NEW;
END;
    $$;


CREATE OR REPLACE TRIGGER trigger_doc_bitacora
    AFTER INSERT ON documentos
    FOR EACH ROW
    EXECUTE PROCEDURE FUNCION_INSERTAR_BITACORA();